version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "3001:3000"
    depends_on:
      - db

  db:
    image: couchbase:latest
    volumes:
      - ../dumps:/tmp/
    ports:
      - "5432:5432"